command: ['streamlit', 'run', 'app.py', '--server.port', '8000', '--server.address', '0.0.0.0']
env:
  - name: 'LAKEBASE_INSTANCE'
    value: 'pl-scout-hub'
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
